vendor/disposable_emails.yml

Would be possible to remove fastmail.fm from the disposable domains? Looks like people use it on a frequent basis

feature/ removed fastmail.fm from disposable emails

---

vendor/disposable_emails.yml

We have issues with existing users that signed up with these 2 email providers.
[Hushmail](https://en.wikipedia.org/wiki/Hushmail)
[Naver (Hangul: 네이버) is a popular sponsored advertisement portal in South Korea, owned by Naver Corporation](https://en.wikipedia.org/wiki/Naver)

Removed hushmail.com and naver.com from disposable emails

---

pull_mailchecker_emails.rb
vendor/disposable_emails.yml

The main domain was removed, so removing the extra domains seems reasonable: https://github.com/lisinge/valid_email2/pull/38

Allow the rest of the hushmail.com domains

---

vendor/disposable_emails.yml

Hi, 
The University of Singapore (http://nus.edu.sg/) is included in your list of disposable email domains. I've removed it in the PR because as far as I know it is a valid domain.
Thanks!

Removed National University of Singapore from the blacklist because it is a valid domain

---

valid_email2.gemspec

Earlier today I created a pull request (https://github.com/lisinge/valid_email2/pull/57) regarding adding a whitelist of MX record (I closed the pull request by the way). One thing I realized was an issue with rake which causes travis check to fail. You can actually see the related failure here:
https://travis-ci.org/lisinge/valid_email2/jobs/183442214
This is a fix for it. Thanks

Fix compatibility issue with rake on travis

---

lib/valid_email2/address.rb

I need to analyse thousands of domains and it takes much time.
Some experiments:
```ruby
def domain_is_in?(domain_list)
domain_list.select { |domain|
address.domain =~ (/\A(.*\.)*#{domain}\z/i)
}.any?
end
def domain_is_in_2?(domain_list)
domain_list.any? { |domain|
address.domain =~ /\A(.*\.)*#{domain}\z/i
}
end
def domain_is_in_3?(domain_list)
address_domain = address.domain.downcase
domain_list.any? { |domain|
address_domain =~ /\A(?:.+\.)*?#{domain}\z/
}
end
def domain_is_in_4?(domain_list)
address_domain = address.domain.downcase
domain_list.any? { |domain|
address_domain.end_with?(domain) && address_domain =~ /\A(?:.+\.)*?#{domain}\z/
}
end
```
Code:
```ruby
a = ValidEmail2::Address.new 'alex...@gmail.com'
n = 100
Benchmark.bm do |x|
x.report { n.times do ; a.disposable?; end } …
```

Improve performance of checking domains

---

vendor/disposable_emails.yml

I ran your disposable domain database against our own and found many false positives for Chinese email domains. I dug and found they'd been removed from mailchecker. So I modified and ran the update script locally to not keep the existing domains, filtered to just removed domains, and then searched the mailchecker history (with `git log -p -S domain -- list.json`) to verify they had been removed and where.
https://github.com/FGRibreau/mailchecker/commit/17af0c523187b37442896c9b5ab4a6b65fa1cf8d
126.com
163.com
sina.com
sohu.com
vip.163.com
vip.qq.com
vip.sina.com
https://github.com/FGRibreau/mailchecker/commit/fa7696d8cdf4e40d5092f2055c86af5bfd22b80a
disposableemailaddresses:emailmiser.com
https://github.com/FGRibreau/mailchecker/commit/df525b922362e35f58a4a0665ddb6a9b9107135d
yeah.net

Remove disposable domains that were removed from mailchecker

---

.travis.yml
README.md
gemfiles/activemodel4.gemfile
gemfiles/activemodel5.gemfile
lib/email_validator.rb
lib/valid_email2.rb
lib/valid_email2/email_validator.rb
spec/valid_email2_spec.rb

This is a breaking change. The invocation changes from:
```
validates :email, email: true
```
to
```
validates :email, 'valid_email_2/email': true
```
This solves https://github.com/lisinge/valid_email2/issues/46

Namespace EmailValidator under the ValidEmail2 namespace.

---

vendor/disposable_emails.yml

This is a valid email provider, mainly used in Asia.
https://www.quora.com/Are-QQMail-accounts-permanent
I've mentioned this on #96 - Until we get this figured out (or not!), I've figured we might as well remove this domain.

Remove qq.com from disposable_emails.yml

---

vendor/disposable_emails.yml

[https://protonmail.com/](https://protonmail.com/) is a valid email provider.

Remove protonmail.com from disposable emails

---

lib/valid_email2/address.rb
spec/valid_email2_spec.rb

[Issue-93](https://github.com/lisinge/valid_email2/issues/93)
If email address contains emoticons then ValidEmail2 was returning true. 
`
ValidEmail2::Address.new("abc🙈@bbc.com").valid? => true
`
It should return false.
I just fixed this issue. Please review the PR.

ValidEmail2 return false if email contain emoticons in email

---

lib/valid_email2/address.rb
spec/valid_email2_spec.rb

In section 5.1 of https://tools.ietf.org/html/rfc5321
> If an empty list of MXs is returned, the address is treated as if it was associated with an implicit MX RR
So in other words, checking only MX record is not enough.

Allow case of MX record fallback to A record

---

README.md
lib/valid_email2/address.rb
lib/valid_email2/email_validator.rb
spec/valid_email2_spec.rb

Some well known email providers, such as Gmail, support email address tagging (example+hello@gmail.com --> example@gmail.com). This is a really great feature, but also causes problems to manage user accounts (e.g. duplicates).
This PR provides the feature to forbid email address tagging. By default email address tagging is allowed. 
To validate that the email address is not tagged add this to your ActiveModel:
```
validates :email, 'valid_email_2/email': { forbid_tagging: true }
```
**Without ActiveModel:**
```
address = ValidEmail2::Address.new("example+hello@gmail.com")
address.tagged? => true
```
It would be nice to merge this PR to this great gem.

Forbid address tagging

---

README.md
lib/valid_email2.rb
lib/valid_email2/address.rb
lib/valid_email2/email_validator.rb
spec/valid_email2_spec.rb

Hi! I was looking at https://github.com/lisinge/valid_email2/pull/112 and seems like you prefer the way to whitelist with something similar to blacklist, so I made some.
Happy to tweak if this is not what you're looking for. It would be really nice to have some official whitelist way. Thanks!

Add feature to whitelist disposable domains with vendor/whitelist.yml

---

config/disposable_email_domains.yml

Adds desoz.com to disposable_email_domains.yml. Seeing disposable spam accounts created with this domain.

Add desoz.com to disposable_email_domains.yml

---

README.md

- Improved the Readme to contain:
- A stub for the `mx` part of the  `disposable` validation.
- A note in the v3 update section regarding the above.
- Change the stubs to use `and_return` instead of a block

Readme: Add disposable stub and extend the v3 update section 

---

README.md

The link in the Readme gave a 404, so I fixed it.

Fix link in Readme to disposable_email_domains.yml

---

lib/valid_email2/address.rb
spec/valid_email2_spec.rb

Email addresses are invalid if they have a '.@' consecutively and email systems will not send to addresses that are typed like that, but currently valid_email2 does not check for that issue. Hopefully you agree that this is a valid check that should be added and it can help out anyone else who may be having this issue :).

add full address check for .@ as it is not allowed

---

config/disposable_email_domains.yml

I'm using this domain for my company now with a commercial email provider (Fastmail). Previously we parked the domain and used it to dump junkmail in Mailinator. WPVulnDB and likely others blacklist domains in here. As we'd like to avoid being blacklisted in the future, I'm filing this pull request.

xwaretech.com no longer points to mailinator

---

lib/valid_email2/address.rb
spec/valid_email2_spec.rb

This PR corrects the following behavior in the gem:
Email addresses whose domain names begin or end with a "-" are currently being handled as valid email addresses.
For example:
* `foo@-gmail.com`
* `foo@gmail-.com`
Let me know what you think! Thanks in advance.

Validate that domain name cannot begin or end with a dash

---

lib/valid_email2/address.rb
spec/valid_email2_spec.rb

After 3.0.1 was released the following passes validation:
```
user@gmail .com
```
Spaces should not allowed in the domain part.
https://en.wikipedia.org/wiki/Email_address#Examples
This PR fixes this.

Validate that spaces cannot exist in the domain

---

README.md
lib/valid_email2/address.rb
lib/valid_email2/email_validator.rb
spec/valid_email2_spec.rb

Users may want the ability to only check for a disposable domain, without an additional check for the MX server - there's a trade off between the value of the extra check for the MX server and the time saved by not making that check (because of the call to the DNS resolver).
Currently, you can only get this functionality by doing something like this:
```
a = ValidEmail2::Address.new(address)
disposable_domain = a.valid? && a.send(:domain_is_in?, ValidEmail2.disposable_emails)
```
My proposed PR would keep the `disposable?` method but also have separate methods for `disposable_domain?` and  `disposable_mx_server?`. You can also pass in `disposable_domain: true` into the `options` hash if you don't want to check the `mx_server` during the `disposable` check.

Ability to check for disposable domain without MX server check

---

lib/valid_email2/address.rb
spec/valid_email2_spec.rb

Currently, the code allows for a forward slash in the email address domain, but this should be a prohibited character. This pull request addresses that.
**How to test**
If you set the changed `PROHIBITED_DOMAIN_CHARACTERS_REGEX` constant in `ValidEmail2::Address` back to its current value:
```PROHIBITED_DOMAIN_CHARACTERS_REGEX = /[+!_\s]/```
you will see that the new test I have added fails.

Adding forward slash to list of prohibited domain characters

---

lib/valid_email2/address.rb
lib/valid_email2/email_validator.rb
spec/valid_email2_spec.rb

- Resolves #36
- Add `disallow_dotted` option to enable validation of locals with dots
- Add `dotted?` method to check if a local includes a dot

Validate that locals do not include dots. Fixes #36

---

config/disposable_email_domains.txt

They belong to 1&1 Mail & Media GmbH

Remove gmx.com and gmx.es from disposable email domains

---

lib/valid_email2/address.rb

On some SMTP servers you are not allowed to send mails to UTF-8 addresses. On my side its not allowed
to have "umlaut" in domain part.
This patch allows you to change the prohibited_domain_characters_regex such as a initalizer:
```ruby
ValidEmail2::Address.prohibited_domain_characters_regex = /[+!_\/\s'`äöüÖÄÜß]/
```

Make prohibited_domain_characters_regex changeable

---

README.md
lib/valid_email2/email_validator.rb
spec/valid_email2_spec.rb

In some cases you want to check multiple email fields:
```ruby
class Invoice
validates :receivers, 'valid_email_2/email': { mx: true, disposable: true, multiple: true }
end
Invoice.new(receivers: "invoices@google.com,accounting@google.com")
```
Each other option will check for each address.

Allow multiple addresses separated by comma

---

lib/valid_email2/address.rb
spec/valid_email2_spec.rb

https://en.wikipedia.org/wiki/Email_address#Validation_and_verification
`dot ., provided that it is not the first or last character and provided also that it does not appear consecutively (e.g., John..Doe@example.com is not allowed).[8]` 
Or you can see it in https://www.rfc-editor.org/rfc/inline-errata/rfc3696.html (search by "consecutive")

added an option that disallow a consecutive dots

---

lib/valid_email2/address.rb
spec/valid_email2_spec.rb

Great little gem! I'm looking forward to trying it out on my next project.
Going through the list of open issues, I noticed that https://github.com/micke/valid_email2/issues/164 wouldn't be a lot of work so I threw together a quick PR. Please let me know if it's acceptable :bow:

Invalidate dot-starting emails

---

config/disposable_email_domains.txt

`vp.com` does not appear to be a disposable domain. We've had a legitimate user try and sign up with this email address and I also verified this using Mailgun's validator.

Remove vp.com from disposable_email_domains.txt

---

README.md
lib/valid_email2/email_validator.rb
spec/valid_email2_spec.rb

Hello,
I added a config option for `disposable_domain_with_whitelist` which allows for checking only `disposable_domain?` against the whitelist without checking for MX servers.
Also fixed a spec that was incorrect - `is valid if the domain is disposable but in the whitelist` was incorrectly passing that `user.valid?` was `falsy` due to `ValidEmail2.whitelist` being cached to an empty set.
I used `instance_variable_set` in the spec to avoid having to change `valid_email2.rb` to allow whitelist setting, I can do that instead if you prefer.

Whitelisted disposable domains

---

config/disposable_email_domains.txt

This doesn't seem to be a disposable email domain. From Mailgun validation:

Remove webdesignspecialist.com.au from disposable email domains

---

README.md
lib/valid_email2/address.rb
lib/valid_email2/email_validator.rb
spec/valid_email2_spec.rb

This resolves #118 by allowing the user to validate either strictly on the presence of MX records, or by following a strict reading of RFC 5321 and considering an A record as a valid mail destination.

Add strict_mx validation

---

config/disposable_email_domains.txt

Adding `biyac.com` to disposable email list.
This web [https://tempail.com](https://tempail.com) is offering disposable email under the domain `biyac.com`

Add biyac.com as disposable email domain

---

lib/valid_email2/email_validator.rb
spec/valid_email2_spec.rb

If one tried to pass an array of emails for validation instead of a csv
string, validation would fail, as it would try to apply string methods
to an array. This fix supports both csv strings and email arrays.

Fix an issue with validating an email array

---

config/disposable_email_domains.txt

Original site:  https://mailpoof.com/

fix: adding mailpoof.com to the list

---

README.md
lib/valid_email2/address.rb
lib/valid_email2/email_validator.rb

Ready for feedback on how I put this together to set a default 5s DNS timeout.
I didn't add any fresh tests to cover this because I'm not sure offhand how to mock that in rspec, but I can dig into that if needed and the API is acceptable.
resolves #180
thanks!

set a DNS timeout

---

config/disposable_email_domains.txt

Remove onit.com from the disposable domain list

---

config/disposable_email_domains.txt

This is a legitimate company website.

Remove asics.com from the disposable domain list

---

config/disposable_email_domains.txt

This is a legitimate free email service.

Remove freemail.hu from the disposable domain list

---

config/disposable_email_domains.txt

This is a free email service which runs by China Mobile.

Remove 139.com from the disposable domain list.

---

lib/valid_email2/address.rb
spec/address_spec.rb

This change makes sure that `ValidEmail2::Address#valid?` always returns a boolean, and not nil which it currently returns when the input is not valid (e.g. empty or no domain).
I added a few specs for `ValidEmail2::Address` and explicitly test for true/false (not truthy/falsey).

ValidEmail2::Address#valid? always returns a boolean, also for invalid addresses

---

README.md

I'm currently using the extremely simple Devise regex (`/\A[^@\s]+@[^@\s]+\z/`) for validating emails, and an email like `foo.@example.com` (notice the dot right before @)  snuck in as valid when it's not.
In exploring ways to catch this, I stumbled onto this library and on first read of the docs, I took the `disallow_dotted` option to mean literally a dot right before @ (as my example showed), as opposed to anywhere before the @. The fact that it's an optional feature, and not the default, gave me pause of whether a dot right before the @ might sometimes be valid if it's the user's choice to enable this or not, sending me into the code to understand how the option is implemented.
Now it's clear that it rejects the email if there's dots anywhere before the @, not just literally right …

Clarify `disallow_dotted` applies to anywhere before the @

---

lib/valid_email2/email_validator.rb

"regex: true" appears to not be used in the code base, so removed it.
test plan: ran tests, tests pass.

Remove option 'regex' from default_options as it doesn't seem to be used

---

config/disposable_email_domains.txt

These domains are not disposable domains :
- dralias.com
- aleeas.com
- 8alias.com
- 8shield.net
- slmail.me
- simplelogin.fr
- lilo.org
Resolves issue #199

Remove domains that are not disposable domains

---

config/disposable_email_domains.txt

Remove mozmail.com from disposable email domains

---

config/disposable_email_domains.txt

Fix (partially) #211 by allowing custom domains managed by [SimpleLogin](https://simplelogin.io/).

Remove simplelogin.co from disposable email domains

---

config/disposable_email_domains.txt

Follow-up to #212, fix (partially) #211 by allowing aliases managed by [SimpleLogin](https://simplelogin.io/).

Remove Simplelogin aliases from disposable email domains

---

lib/valid_email2/email_validator.rb
spec/valid_email2_spec.rb

Makes it possible to have a dynamic error message like:
```ruby
class SomeForm
include ActiveModel::Model
validates :email, 'valid_email_2/email' => {
mx:         true,
blacklist:  true,
disposable: true,
message:    -> { I18n.t('errors.registration.disposible_email') }
}
end
```

Allow dynamic error message via Proc or Lambda

---

README.md
lib/valid_email2/address.rb
lib/valid_email2/email_validator.rb
spec/valid_email2_spec.rb

Adds an option for easily customising the DNS resolver that is used for checking A and MX records.
If no option is given, it will use all current defaults.

Add `dns_nameserver` option for mx checking

---

config/disposable_email_domains.txt

[Mailinblack](mailinblack.com) is not a disposable email service but a spam/fishing protector.

feat: remove mailinblack.com from disposable

---

config/disposable_email_domains.txt

According to our customer and check-domain this is not disposable https://check-mail.org/domain/kommespaeter.de/

remove valid domain https://check-mail.org/domain/kommespaeter.de/

---

config/disposable_email_domains.txt
pull_mailchecker_emails.rb

net.ua is a root domain and should not mark as disposable email domain.
It blocks all domains in that zone.
https://www.net.ua/uk/

Remove net.ua from disposable email domains

---

config/disposable_email_domains.txt

hi,
a user complained that his email cant be used. looks reasonable https://check-mail.org/domain/alpenjodel.de/

remove valid domain alpenjodel.de

---

config/disposable_email_domains.txt

A user complained that he could not register. The domain is supposed to be OK https://check-mail.org/domain/directbox.com/

remove directbox.com

---

README.md

Just noticed that this is the consequence of [my update](9df0bf8c9912721b007e5a6acc67f533ca560c9f) to the README:
This PR changes the above to the following:

Add missing linebreak to README

---

README.md

readme indicated a wrong path for denying email domains

fix: typo in readme about config file to deny email domains

---

config/disposable_email_domains.txt
pull_mailchecker_emails.rb

A customer me informed that this is a valid business domain. Apparently it was Sprint, then sprint changed its name to Embarq, and now it is grandfathered in and managed by Centurylink.

Remove  embarqmail.com from disposible list

---

lib/valid_email2/email_validator.rb
spec/valid_email2_spec.rb

- Updated email_validator to strip trailing whitespace from emails when the `multiple` option is enabled.
- Added a test case to ensure emails with trailing whitespace are considered invalid.
Stripping on sanitized values make sense with the multiple option is activated and the input is an string. Otherwise it can lead into emails being stored with trailing whitespace on the DB.

fix(email_validator): handle trailing whitespace in emails

---

lib/valid_email2/address.rb
lib/valid_email2/dns_records_cache.rb
spec/address_spec.rb
spec/spec_helper.rb
spec/valid_email2_spec.rb

Closes https://github.com/micke/valid_email2/issues/179.

Cache MX and A server lookups

---

README.md
lib/valid_email2/address.rb
spec/address_spec.rb
valid_email2.gemspec

https://github.com/micke/valid_email2/pull/257
In this PR, changes are being made to prevent Scandinavian characters from being judged as emoji.
However, this method had a large impact on the validity of email addresses, and for example, email addresses containing Japanese characters were erroneously determined to be VALID.(The expected value is INVALID).
I made the following changes.
- Basically, do not allow multibyte characters
- If you want to allow multibyte characters, set it explicitly
```ruby
ValidEmail2::Address.permitted_multibyte_characters_regex = /[ÆæØøÅåÄäÖöÞþÐð]/
```

Fix false multibyte character detection

---

README.md

@micke 
Thank you for this wonderful gem.
This gem has been very helpful for our product.
I made two additions to the README.
First, I added an example of how to write YAML files. While testing it, I found the specification to be very simple, but some OSS might require nested structures. I clarified this point in the documentation.
Second, since the methods available in the Address class were not all listed, I added a link to address.rb.
Please could you review.
Thanks.

Add YAML format example and API reference link to README

---

config/disposable_email_domains.txt

Removes `nytimes.com` from the list of disposable domains

Remove nytimes.com from list of disposable domains

---

config/disposable_email_domains.txt

This is a PR to address the request to remove buildingradar.com from the disposable email list in this issue:
https://github.com/micke/valid_email2/issues/281
CC: @eldenw28

remove buildingradar.com from disposable list

---

lib/valid_email2/address.rb

@nijikon could you use this branch and check if that works as expected?

FIX: re-add mx_server_is_in?(domain_list) for backwards compatibility

---

.github/workflows/ci.yaml

...and skip the Ruby 3.4 matrix element for active model 6.

CI: Add Ruby 3.4

---

config/disposable_email_domains.txt

cloudflare.com/net provides valid email forwarding services. The MX domains are on .cloudflare.net. 
This should be affecting a lot of people and treating so many emails as disposable. For example, I have non-disposable emails @saashub.com & @libhunt.com that are being regarded as "disposable" because of including cloudflare.net to the list.

Remove cloudflare.com/net from disposable_email_domains.txt

---

lib/valid_email2/dns.rb

While browsing latest gem changes I noticed that config returned by Resolv::DNS::Config.default_config_hash in 
https://github.com/micke/valid_email2/blob/dec511fab0c1a0f7da71c09aa5a3bbaa1e3ca43b/lib/valid_email2/dns.rb#L66-L67
is mutated.
This will be a problem with resolv gem 0.6.1 because on linux it can return frozen hash:
https://github.com/ruby/resolv/blob/6b57765f8ddc46b408aa3b222d1b372fdf1881b2/lib/resolv.rb#L1018

Do not modify config returned by Resolv::DNS::Config
